services:
    server:
        build: .
        restart: on-failure
        ports: 
            - "80:8080"

    db:
        image: postgres
        restart: on-failure
        environment:
            POSTGRES_PASSWORD: mypostgre
            POSTGRES_USER: lua_user
            POSTGRES_DB: luadb
        volumes:
            - db-data:/var/lib/postgresql/data

volumes: 
    db-data: