all:
    hosts:
        remote:
            ansible_connection: ssh
            ansible_user: ec2-user
            ansible_host: 172.31.12.187
            ansible_port: 22
            ansible_ssh_private_key_file: /var/lib/jenkins/cicd/ssh/secret/docker-slave-key.pem